# Jekyll configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 10
language: 'en-uk'

include: ["_pages"]
permalink: /:year/:month/:title/

# Website info
name: LSE Law Review Blog
description: A student-run law journal seeking to provide a platform for high quality legal scholarship.

google_analytics: UA-69281367-1
disqus: 'lse-law-review'
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: '/blog-v2/'

# Permalinks
# permalink: /author/:username
# permalink: /tag/:tag

# gems and other configs
plugins: [jekyll-paginate]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise

defaults:

  - scope: 
      path: '_posts'
    values:
      subclass: 'post tag-test tag-content'
      cover: 'assets/images/banner3.jpg'
  - scope:
      path: '_pages'
    values:
      layout: 'page'
      cover: 'assets/images/banner3.jpg'

authorcategories:
    editor:
      name: "Notes Editors"
    contributor:
      name: "Contributors"


safe: false
lsi: false
branch: master
production_url:  https://ml24330.github.io/blog-v2/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - node_modules
  - .git
